[tox]
min_version = 4.0
envlist = 
    py314-django{61, 60, 52}
    py313-django{61, 60, 52}
    py312-django{61, 60, 52}
    py311-django52
    py310-django52
isolated_build = True

[testenv]
runner = uv-venv-lock-runner
commands = python -m django test --settings=tests.settings
dependency_groups = 
    django52: django52
    django60: django60
    django61: django61